name: mediasoup-worker-fuzzer

on: [pull_request, workflow_dispatch]

concurrency:
  # Cancel a currently running workflow from the same PR, branch or tag when a
  # new workflow is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        build:
          - os: ubuntu-22.04
            cc: clang
            cxx: clang++

    runs-on: ${{ matrix.build.os }}

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}
      MEDIASOUP_SKIP_WORKER_PREBUILT_DOWNLOAD: 'true'
      MEDIASOUP_LOCAL_DEV: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # We need to install pip invoke manually.
      - name: pip3 install invoke
        run: pip3 install invoke

      # Build the mediasoup-worker-fuzzer binary (which uses libFuzzer).
      - name: invoke -r worker fuzzer
        run: invoke -r worker fuzzer

      # Run mediasoup-worker-fuzzer for 5 minutes.
      - name: run-fuzzer.sh 300
        run: cd worker && ./scripts/run-fuzzer.sh 300
