name: Pull Request Stats

on:
  schedule:
    - cron: "0 13 * * 1" # Run it every Monday at 1PM UTC.

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 365
          charts: true
          disable-links: false
          sort-by: 'REVIEWS'
